// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6318.Proper.subsystems;

import org.usfirst.frc6318.Proper.RobotMap;
import org.usfirst.frc6318.Proper.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class TankDrive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController frontLeftSpeedController = RobotMap.tankDriveFrontLeftSpeedController;
    private final SpeedController rearLeftSpeedController = RobotMap.tankDriveRearLeftSpeedController;
    private final SpeedController frontRightSpeedController = RobotMap.tankDriveFrontRightSpeedController;
    private final SpeedController rearRightSpeedController = RobotMap.tankDriveRearRightSpeedController;
    private final RobotDrive robotDrive41 = RobotMap.tankDriveRobotDrive41;
    private final AnalogGyro analogGyro1 = RobotMap.tankDriveAnalogGyro1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public AnalogGyro getGyro() {
    	return analogGyro1;
    }
    
    public double getGyroAngle() {
    	return analogGyro1.getAngle();
    }
    
    public void resetGyro() {
    	analogGyro1.reset();
    }
    
    public void set(double left, double right) {
    	robotDrive41.tankDrive(left, right);
    }
    
    public void stop() {
    	robotDrive41.stopMotor();
    }
    
    public void setArcade(double speed, double rotate) {
    	robotDrive41.arcadeDrive(speed, rotate);
    }

}

