// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6318.Proper.commands;

import edu.wpi.first.wpilibj.command.TimedCommand;
import org.usfirst.frc6318.Proper.Robot;
import org.usfirst.frc6318.Proper.subsystems.ScissorLift;

/**
 *
 */
public class RaiseLift extends TimedCommand {

	ScissorLift scissorLift;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


    public RaiseLift() {
        this(0);
    }

    public RaiseLift(double timeout) {
        super(timeout);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.scissorLift);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        scissorLift = Robot.scissorLift;
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	scissorLift.set(-1);
    }


    // Called once after isFinished returns true
    @Override
    protected void end() {
    	scissorLift.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	scissorLift.stop();
    }
}
