// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6318.Proper.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;
import org.usfirst.frc6318.Proper.Robot;

/**
 * Command if we are on the right side of the arena
 * 
 * will be true the switch is our color on the right
 * 
 * else will be false
 */
public class Right extends ConditionalCommand {
	
	String gameData;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Right() {
      super(new RightOnSide(), new Right());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
      gameData = DriverStation.getInstance().getGameSpecificMessage();
    }

    @Override
    protected boolean condition(){
        return gameData.charAt(0) == 'R';//TODO: Auto Generated method stub
    }
}
